En0c 026/main
nation3/app pull request #179
Opened 2023-08-09 19:32 UTC by yahiamarzouk

## Dework Task

## Related GitHub Issue

## Screenshots (if appropriate):

## How Has This Been Tested?

2023-09-02 15:09 UTC, aahna-ashina requested changes
The Wallet Connect dialog is incorrectly showing _under_ the Nation3 dialog.  It should be the reverse.

> ![](https://github.com/nation3/app/assets/95955389/b0a97ae4-0003-4ec6-ac3c-31494a94c241)

2023-09-04 08:22 UTC, yahiamarzouk commented
> The Wallet Connect dialog is incorrectly showing _under_ the Nation3 dialog. It should be the reverse.
> 
> Maybe a z-index problem.
> 
> > ![](https://user-images.githubusercontent.com/95955389/265213054-b0a97ae4-0003-4ec6-ac3c-31494a94c241.png)


https://github.com/nation3/app/assets/94828675/9cb09cdb-25a6-4c7c-b046-1bf0d8e717b5

Done (Y)

2023-09-04 15:29 UTC, aahna-ashina commented on package.json
> +    "@walletconnect/modal": "^2.6.1"
This code should be in the `/ui` folder.

2023-09-05 14:09 UTC, aahna-ashina requested changes

2023-09-05 14:28 UTC, aahna-ashina requested changes
The `yarn.lock` file should be in the `ui` folder.

2023-09-05 15:36 UTC, aahna-ashina approved these changes

2023-09-08 15:25 UTC, aahna-ashina approved these changes

2023-09-08 15:29 UTC, merged