Increase gas limit for `increase_amount` method
nation3/app pull request #222
Opened 2023-12-17 12:34 UTC by biendeveloper

Fixes https://github.com/nation3/app/issues/221

## Dework Task
https://app.dework.xyz/bounties?taskId=a8282a43-2998-44bb-8ab8-105d45daeb31

2023-12-19 06:17 UTC, aahna-ashina requested changes

2023-12-19 06:17 UTC, aahna-ashina commented on ui/lib/ve-token.ts
>    increase_unlock_time: 600000,
```suggestion
  increase_unlock_time: 1_000_000,
```

2023-12-19 06:17 UTC, aahna-ashina commented on ui/lib/ve-token.ts
>    create_lock: 600000,
```suggestion
  create_lock: 1_000_000,
```

2023-12-19 06:17 UTC, aahna-ashina commented on ui/lib/ve-token.ts
>    withdraw: 400000,
```suggestion
  withdraw: 800_000,
```

2023-12-19 06:33 UTC, biendeveloper commented on ui/lib/ve-token.ts
>    create_lock: 600000,
```suggestion
  create_lock: 1000000,
```

2023-12-19 06:33 UTC, biendeveloper commented on ui/lib/ve-token.ts
>    withdraw: 400000,
```suggestion
  withdraw: 800000,
```

2023-12-19 06:34 UTC, biendeveloper commented on ui/lib/ve-token.ts
>    increase_unlock_time: 600000,
```suggestion
  increase_unlock_time: 1000000,
```

2024-01-31 04:11 UTC, aahna-ashina approved these changes

2024-01-31 04:13 UTC, merged