Revamp the config system to use the JSON manifests
nation3/app pull request #34
Opened 2022-06-13 13:13 UTC by wkm97

issue: https://github.com/nation3/app/issues/30

2022-06-14 16:34 UTC, xPi2 approved these changes
LGTM, not tested

2022-06-27 07:39 UTC, aahna-ashina commented
@wkm97 Will this code change require any environment variable adjustments in Vercel?

2022-06-27 07:47 UTC, aahna-ashina commented on ui/.env.goerli
>  NEXT_PUBLIC_BALANCER_NATION_ETH_POOL_TOKEN="0x161D5108C721C85F1Af4D4f6f790AaBAa37268e7"
@wkm97 If we change to the file in `contracts/deployments/goerli.json`, can this `ui/.env.goerli` file be deleted?

2022-06-27 07:47 UTC, aahna-ashina commented on ui/lib/config.ts
> -    // @ts-expect-error ts-migrate(2322) FIXME: Type 'number' is not assignable to type 'string | ... Remove this comment to see the full error message
@wkm97 Looks look you also deleted this TypeScript line? Was that on purpose?

2022-06-27 07:51 UTC, aahna-ashina requested changes
@wkm97 I'm getting an error message when launching your branch on http://localhost:42069/

I'm not sure if this error has anything do do with your code changes, though.

Are you experiencing the same issue?

<img width="1280" alt="Screen Shot 2022-06-27 at 3 50 39 PM" src="https://user-images.githubusercontent.com/95955389/175888361-1f3b3375-3860-4c67-aa4e-8d0e1607a76d.png">

2022-06-27 17:39 UTC, xPi2 commented
@aahna-ashina I think I fixed, let me know if you have any problem now.
I also cleaned the .env files and merged with main.

2022-06-28 14:57 UTC, luisivan approved these changes
Just tried the preview build on Vercel and seems to be working!

2022-06-30 10:59 UTC, aahna-ashina commented
@wkm97 Looks like your branch has merge conflicts that need to be resolved?

2022-06-30 12:23 UTC, aahna-ashina reviewed
@xPi2 I'm no longer getting the warning at the top of the page asking me to switch the Ethereum network.  Was that removed? 

<img width="1280" alt="Screen Shot 2022-06-30 at 8 22 24 PM" src="https://user-images.githubusercontent.com/95955389/176676184-6482f853-f110-421d-8da7-089628d8ba42.png">

I remember earlier that there used to be a message at the top prompting the user to change the network?

Here is how I tested:
```
cd ui
yarn install

cp .env.goerli .env.local
yarn dev
```
Then 
I opened http://localhost:42069/ while connected to the Ethereum mainnet.

2022-06-30 12:27 UTC, aahna-ashina approved these changes

2022-06-30 15:17 UTC, merged