feat(ui): Allows citizens to update their passport signer, also redesigned the passport view
nation3/app pull request #46
Opened 2022-07-15 13:23 UTC by luisivan

Paves the way for citizens to be able to participate in votes on the go, or authenticate themselves at in-person events without carrying a private key with meaningful funds.

![Screen Shot 2022-07-15 at 2 16 48 PM](https://user-images.githubusercontent.com/718208/179230741-3849e71a-0b4c-40b2-9b71-f4d2e2156f9d.png)
![Screen Shot 2022-07-15 at 2 21 59 PM](https://user-images.githubusercontent.com/718208/179231550-dbf3702a-d8bf-4128-8687-6e8833ea9f02.png)

2022-07-16 03:19 UTC, aahna-ashina requested changes
Looks like the Vercel deployment failed.  I get a 404 error when trying to check why at https://vercel.com/nation3/app/6mvAybNNcWFT4p7L6YR3x7drHFm1

<img width="1280" alt="Screen Shot 2022-07-16 at 11 19 21 AM" src="https://user-images.githubusercontent.com/95955389/179337247-db19b351-520c-4a64-abd0-ff95ac2fea23.png">

2022-07-18 12:54 UTC, luisivan commented
TypeScript stuff :D checking

2022-07-19 04:43 UTC, aahna-ashina requested changes
<img width="420" alt="Screen Shot 2022-07-19 at 12 43 11 PM" src="https://user-images.githubusercontent.com/95955389/179666381-c84dfe29-2fa7-46c6-8ba1-2d03070e5e7b.png">

2022-07-19 10:08 UTC, xPi2 commented
I personally don't like floating items over other floating items.
What about making this slight change?
![Screenshot 2022-07-19 at 12 06 56](https://user-images.githubusercontent.com/32301192/179725597-43304f74-02c9-4ad1-a5ed-1e02b77ef9f1.png)

2022-07-19 11:42 UTC, aahna-ashina commented
@luisivan For comparison:  Is this similar to vote delegation, where one account grants another account to vote on its behalf, or is a signer account a different type of thing?

2022-07-21 04:45 UTC, gregfromstl submitted a review, later dismissed

2022-07-21 09:29 UTC, xPi2 approved these changes
![Screenshot 2022-07-21 at 11 26 27](https://user-images.githubusercontent.com/32301192/180180332-9cdbf64a-6041-46d0-a9b8-3093f6f887eb.png)
I'm having this curious bug on some page reloads, but maybe it's only on my end.

2022-07-21 10:06 UTC, luisivan commented
@xPi2 I was having it too but I though it was a problem with my Web3 provider. Looks like it's not, will investigate

2022-07-21 20:01 UTC, gregfromstl commented
@luisivan do you know when this PR will be finalized? I'd like to open a PR merging the migration to the `@nation3/utils` package but it conflicts with these changes.

2022-07-22 08:00 UTC, luisivan commented
Now that I'm at it, I aligned all cards in the the mobile view to have the same width

<img width="449" alt="Screen Shot 2022-07-22 at 8 59 58 AM" src="https://user-images.githubusercontent.com/718208/180392560-63707e3d-1e2d-4daf-aad4-4abf676e2534.png">

2022-07-22 10:27 UTC, xPi2 commented
Looks dope to me. I keep my approval.
Just review the conflicts before merging.

2022-07-22 17:45 UTC, gregfromstl approved these changes

2022-07-22 17:45 UTC, gregfromstl commented on ui/lib/passport-nft.ts
> +  console.log(id)
Can remove

2022-07-24 04:22 UTC, aahna-ashina approved these changes

2022-07-24 04:22 UTC, aahna-ashina commented on ui/lib/passport-nft.ts
> +import PassporNFT from '../abis/Passport.json'
Typo?
```suggestion
import PassportNFT from '../abis/Passport.json'
```

2022-07-24 04:22 UTC, aahna-ashina commented on ui/lib/passport-nft.ts
> +      contractInterface: PassporNFT.abi,
```suggestion
      contractInterface: PassportNFT.abi,
```

2022-07-24 04:22 UTC, aahna-ashina commented on ui/lib/passport-nft.ts
> +      contractInterface: PassporNFT.abi,
```suggestion
      contractInterface: PassportNFT.abi,
```

2022-07-25 10:24 UTC, merged