Migrate App lib to @nation3/utils
nation3/app pull request #59
Opened 2022-07-28 23:28 UTC by gregfromstl

This is a **HIGH RISK** merge. It affects the entire app and has an incredibly wide scope. There will likely be bugs to sort out. Please test thoroughly.

Make sure you have an up-to-date `.env` file.

Test all existing functionality. Passport features need to be tested on rinkeby.

2022-07-29 09:16 UTC, aahna-ashina commented
@gregfromstl I think a code conflict in `ui/lib/passport-nft.ts` needs to be resolved first?

2022-07-29 09:35 UTC, aahna-ashina commented on package-lock.json
> +}
Is this file necessary?

2022-07-29 09:40 UTC, aahna-ashina requested changes
There is a merge conflict.

2022-07-29 09:43 UTC, aahna-ashina commented
@gregfromstl This is a lot of file changes in one pull request.  Do you think it would be possible to handle the migration more gradually, for example by doing only one page at the time or something like that?  Or is it only possible to do everything at once?

2022-07-29 10:06 UTC, johnmark13 commented
Or, is it possible to break this into two PRs. One PR for everything up to the last commit which looks like bug fixes and then another PR for the last commit that introduces the utils change?

I may have trivialised how interlocked the commits are but for example the change `if (!nationBalance && !veNationBalance) return` looks like something that could have been done/tested/released immediately as a bug fix that is actually not related to this migration?

2022-07-29 13:37 UTC, luisivan commented
Few things:
- Seems like it's using external RPC providers instead of injected, in case there's one that's injected. Because of it, I'm getting CORS errors and nothing works
- Connecting and disconnecting an account doesn't work (I see a `TODO` message logged in the console while trying to disconnect)

2022-07-29 15:06 UTC, gregfromstl commented
> @gregfromstl This is a lot of file changes in one pull request. Do you think it would be possible to handle the migration more gradually, for example by doing only one page at the time or something like that? Or is it only possible to do everything at once?

We likely have to do everything at once. This uses a WagmiProvider from the utils package rather than directly within the app. If we kept any of the wagmi imports directly in the app, it would require a different version (had to rollback for the utils package), causing all kinds of issues.

2022-07-29 15:07 UTC, gregfromstl commented
> Or, is it possible to break this into two PRs. One PR for everything up to the last commit which looks like bug fixes and then another PR for the last commit that introduces the utils change?
> 
> I may have trivialised how interlocked the commits are but for example the change `if (!nationBalance && !veNationBalance) return` looks like something that could have been done/tested/released immediately as a bug fix that is actually not related to this migration?

The last PR was incorporating changes from a commit to main that came after everything else was done. I added two new hooks to the utils package and was just re-adding that functionality to the migrated version of the app.

2022-07-29 15:10 UTC, gregfromstl commented
> There is a merge conflict.

Resolved

2022-07-29 15:12 UTC, gregfromstl commented
@aahna-ashina do you know what's going on with the CI build

2022-07-29 15:16 UTC, gregfromstl commented
> Few things:
> 
> * Seems like it's using external RPC providers instead of injected, in case there's one that's injected. Because of it, I'm getting CORS errors and nothing works
> * Connecting and disconnecting an account doesn't work (I see a `TODO` message logged in the console while trying to disconnect)
<img width="316" alt="Screen Shot 2022-07-29 at 10 13 17 AM" src="https://user-images.githubusercontent.com/17715009/181790233-7d09248c-2056-4410-b5f6-acd42465abe8.png">
Injected is being used if you check the `connectors` file in `shared/utils`. How do you know injected isn't being used? I'm not getting any CORS errors.

Good catch with disconnect, I meant to add that

2022-07-29 15:31 UTC, gregfromstl commented
@luisivan disconnect is fixed

2022-07-29 16:20 UTC, johnmark13 commented
On the whole I think reviewing a PR like this should be about the application of coding standards and sanity checking nothing screaming "wrong" at the reviewer and on that basis I would approve the PR.

I'd have very moderate concerns that there are functional changes mixed in with the migration as that will make it harder to understand if the migration or the functional change (albeit they all look like fixes) changes behavior of the app. A trivial example of this is `downloadPassURI` where the code would have used to explode but now calls the endpoint with an undefined value, which could cause a different undefined behaviour. (That URI construction should move anyway to facilitate testing and multiple passport types, def a separate issue 😉 ). It's also best not to be too dogmatic!

As it looks like everyone is looking at the PR though and testing it for themselves, I think I am not needed, congratulations on what looks like an entertaining journey 💯

2022-07-30 04:13 UTC, aahna-ashina commented
> > @gregfromstl This is a lot of file changes in one pull request. Do you think it would be possible to handle the migration more gradually, for example by doing only one page at the time or something like that? Or is it only possible to do everything at once?
> 
> We likely have to do everything at once. This uses a WagmiProvider from the utils package rather than directly within the app. If we kept any of the wagmi imports directly in the app, it would require a different version (had to rollback for the utils package), causing all kinds of issues.

@gregfromstl Got it.  What if we upgrade the wagmi version in the app, so that the wagmi version is the same in the app and in the utils library, _before_ doing the migration?  Would that make things less complicated?

2022-07-30 04:30 UTC, aahna-ashina commented
> @aahna-ashina do you know what's going on with the CI build

@gregfromstl I compared the two branches, and I think the CI is failing because your branch contains a `package-lock.json` file.  The CI only expects the `yarn.lock` file to be present, which is the case on the main branch.

Maybe you can try using `yarn add <package>` instead of `npm install <package>`, and then delete the `package-lock.json` from your branch?

For context, see https://github.com/nation3/app/commit/eec0d97640e4db3c36054292c3670242243de95a and https://discord.com/channels/690584551239581708/963778898389237800/984017995913379871

2022-07-30 04:40 UTC, aahna-ashina requested changes
I suggest deleting `package-lock.json`, assuming we want to use Yarn instead of NPM.

2022-07-31 18:30 UTC, gregfromstl commented
> > > @gregfromstl This is a lot of file changes in one pull request. Do you think it would be possible to handle the migration more gradually, for example by doing only one page at the time or something like that? Or is it only possible to do everything at once?
> > 
> > 
> > We likely have to do everything at once. This uses a WagmiProvider from the utils package rather than directly within the app. If we kept any of the wagmi imports directly in the app, it would require a different version (had to rollback for the utils package), causing all kinds of issues.
> 
> @gregfromstl Got it. What if we upgrade the wagmi version in the app so that the wagmi version is the same in the app and in the utils library, _before_ doing the migration? Would that make things less complicated?

The package wagmi version is a *rollback*. We can't use the latest version of wagmi since it breaks npm's dependency tree when used as a subdependency. Now, we could rollback the version of wagmi in the app, then replace the wagmi calls with nation3/utils ones piece by piece. But that would still require app-wide changes to update the wagmi version.

2022-07-31 19:13 UTC, closed without merging

2022-08-01 10:26 UTC, luisivan commented
@gregfromstl are you planning on re-opening this PR later?